#!/bin/bash

install_location=$(pwd)

npm install -g bower
npm install -g grunt-cli

# When adding branches, ensure a same-named branch exists in fifthweek/fifthweek-web-test-machine-logs

echo "20 * * * * (cd $install_location ; ./test-branch restyle)" | sort - | uniq - | crontab -
