#!/bin/bash

install_location=$(pwd)

npm install -g bower
npm install -g grunt-cli

git config --global user.name "Fifthweek Services"
git config --global user.email services@fifthweek.com

# When adding branches, ensure a same-named branch exists in fifthweek/fifthweek-web-test-machine-logs

echo "00 20 * * * (cd $install_location ; ./test-branch-with-env restyle)" | sort - | uniq - | crontab -
