#!/bin/bash

cd ..
branch=$0
home=$(pwd)/fifthweek-web-tests-$branch

rm -rf $home
mkdir $home

log=$home/fifthweek-web-test.log
log_commit_message="Commit undetermined"

exec >$log 2>&1

{ # TRY

  git clone -b $branch git@github.com:fifthweek/fifthweek-web.git $home/fifthweek-web
  cd $home/fifthweek-web

  log_commit_message="$(git log -1 --pretty=%B) - $(git rev-parse --short HEAD)"

  npm install
  bower install --config.interactive=false

  # grunt ptest:live:dist:browserstack

  log_commit_message="PASS: $log_commit_message"

} || { # CATCH 

  log_commit_message="FAIL: $log_commit_message"

}

# FINALLY

git clone -b $branch git@github.com:fifthweek/fifthweek-web-test-machine-logs.git $home/fifthweek-web-test-machine-logs
rm -rf $home/fifthweek-web-test-machine-logs/*
cp $log $home/fifthweek-web-test-machine-logs/fifthweek-web-test.log

cd $home/fifthweek-web-test-machine-logs

git add -A
git commit -m "$log_commit_message"
git push
