#!/bin/bash

cd ..
branch=$1
home=$(pwd)/fifthweek-web-tests-$branch

rm -rf $home
mkdir $home

log=$home/fifthweek-web-test.log
log_commit_message="Commit undetermined"

exec >$log 2>&1

{ # TRY

  git clone -b $branch git@github.com:fifthweek/fifthweek-web.git $home/fifthweek-web
  cd $home/fifthweek-web

  log_commit_message="$(git log -1 --pretty=%B) - $(git rev-parse --short HEAD)"

  npm install
  bower install --config.interactive=false

  # grunt ptest:live:dist:browserstack

  success_mode="Success"
  icon_emoji=":white_check_mark:"

} || { # CATCH 

  success_mode="Failure"
  icon_emoji=":no_entry:"

}

# FINALLY

git clone -b $branch git@github.com:fifthweek/fifthweek-web-test-machine-logs.git $home/fifthweek-web-test-machine-logs
rm -rf $home/fifthweek-web-test-machine-logs/*
cp $log $home/fifthweek-web-test-machine-logs/fifthweek-web-test.log

cd $home/fifthweek-web-test-machine-logs

git add -A
git commit -m "$success_mode: $log_commit_message"
git push

curl -X POST --data-urlencode 'payload={"username": "Fifthweek Full Test Suite", "text": "'"$success_mode"': '"$log_commit_message"'", "icon_emoji": "'"$icon_emoji"'"}' https://hooks.slack.com/services/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
